### ISSUE TITLE
Change Label from 'API Base URL' to 'Instance URL' in Settings Page

### ISSUE THREAD

**Issue by iAnonymous3000** [scidsg/mastodon-scheduler#72]
On the settings page of the Mastodon Scheduler application, the field for the Mastodon instance is currently labeled as "API Base URL". This label can be confusing for users who are not familiar with the terminology of API or Base URL. Therefore, I suggest that the label be changed to "Instance URL". This new terminology is more intuitive and it directly refers to the Mastodon instance URL that users are connecting to.

**Comment by glenn-sorrentino** [comment]
Updated!
